### PR TITLE
allow creation of multiple access tokens per client id

### LINKED ISSUE #64: Only one connection allowed
With OAuth2, you can have only one active connection per Registered clients, it seems.

Steps to reproduce:
Try to log in with two clients on different computer with the same account. 

Expected behavior: 
Both clients can be connected at the same time

Actual behavior:
Only one client stays connected. The other client is getting disconnected.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #64

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> Does that make sense?

Absolutly! Thanks a lot for pointing this out.

Lets add a relationship between refresh token and access token - similar to https://github.com/thephpleague/oauth2-server/blob/master/src/Entities/RefreshTokenEntityInterface.php#L42-L54

**Comment by ogoffart** [comment]
I tested the use case of the client with several time the same account (which should not really be supported use case), and it works fine :+1: .

The surprising thing is that even restarting the client works fine despite the fact that, as I mention in https://github.com/owncloud/client/issues/5830#issuecomment-318583294 , the client only store one `refresh_token` in the keychain.  Meaning that the refresh_token can be re-used several times.  Is that expected that one can re-use the `refresh_token` ?

**Comment by DeepDiver1975** [comment]
> Is that expected that one can re-use the refresh_token ?

the refresh token is deleted after use - see https://github.com/owncloud/oauth2/pull/65/files#diff-db452df3926cad18dfda329e7e3fddf4R176

something not working properly here?

**Comment by SamuAlfageme** [comment]
>  Is that expected that one can re-use the refresh_token ? 

I'd say no, they have to maintain a 1-1 rel. with the `auth_token`

The `refresh_token` shouldn't be universal for an account... Imagine the scenario where we want session-level management (i.e. what GMail/Facebook do; there might be many sessions opened by the same user in the same clients but in different locations/devices); we should be able to revoke both tokens at a time.

**Comment by ogoffart** [comment]
The client does two POST to the `token` endpoint at the same time,  with the same `refresh_token`.  Both succeeds and return different new access_token and refresh_token.
Maybe there is a race condition?

**Comment by DeepDiver1975** [comment]
> The client does two POST to the token endpoint at the same time,

can you test this with consecutive calls?

**Comment by SamuAlfageme** [comment]
> Both succeeds and return different new access_token and refresh_token. 

I run the scenario quite some times now and I saw that reproduced a few of them. So the race is to be considered, yes. 

> can you test this with consecutive calls?

And those times the requests don't reach the server that simultaneously, the first POST succeeds; second is replied:

```
{
    "error": "invalid_grant"
}
```
... and the client pops-up a new browser to Authorize the app again. So after all, **we might need to adapt client-side for the edge-case** in https://github.com/owncloud/client/issues/5830 😕 (i.e. one of the logged-in accounts is left unauthorized upon client restart).

Also, if we space in time the POST requests to `https://<server>/index.php/apps/oauth2/api/v1/token` wouldn't the second one use the access token the first just got... **and succeed** (invalidating & overwriting the one just used)? 

That will never happen in the scenario of 2 independent clients sharing the same `id/secret` with the same account connected as it's inherent to this refresh-token-shared-between-accounts issue.

cc/ @ogoffart @DeepDiver1975

**Comment by DeepDiver1975** [comment]
let me rebase this ....

**Pull request merged**
