### PR TITLE
Check user status

### PR DESCRIPTION
**Pull request by jvillafanez**
Handle the case where the user associated to the token is disabled. Both the authorization_code and refresh_token will fail with a 400 status and a "unauthorized_client" error instead of returning a valid access token

Related to https://github.com/owncloud/client/issues/7212 and https://github.com/owncloud/enterprise/issues/2509

### CODE REVIEW

**Comment by jvillafanez** [comment]
There is some piece still missing. The desktop client opens the url below, which keeps reloading it self over and over.
Screen Shot 2019-05-31 at 14 46 35
I guess the session is still active, and that's why the browser doesn't redirect to the login page until the session is invalidated at some point.

**Comment by jvillafanez** [comment]
I'll need confirmation that the problem (https://github.com/owncloud/oauth2/pull/209#issuecomment-497697031) is caused by core and not by the oAuth2 app. I suspect a middleware trying to login with a token / cookie or similar and core is rejecting the request because the user is disabled. The request doesn't seem to reach the PageController of the oAuth2 app, or at least I don't see how that code could fail like that there.
It's very likely that the session is still valid even with the user being disabled.

**Comment by DeepDiver1975** [comment]
If you want to logout the user you have to call \OC::$server->getUserSession()->logout()

**Comment by HanaGemela** [comment]
The 'User disabled' page still reloads with 
Client: 2.6.0 (build 12703)
macOS 10.15
Server 10.3.0 stable
oAuth2 0.4.2RC3

Steps to recreate:
1) Login with oAuth2 using enabled user
2) Let the desktop client sync
3) Quit the client
4) Disable user
5) Start the desktop client

It will eventually stop reloading and login page will be shown but till then the page reloads over and over again

**Comment by micbar** [comment]
@HanaGemela Thank you for testing.

This is a little bit ugly behaviour ;-)

**Comment by HanaGemela** [comment]
Getting 400 error instead of 200 now. So the original bug has been resolved. But the reloading page still needs fixing

**Comment by DeepDiver1975** [comment]
Please open a new issue instead of commenting on a closed PR. This helps to track this better. THX

**Pull request merged**
