### PR TITLE
Print displayname of the user in the switch user page

### LINKED ISSUE #74: Accounts from the LDAP user backend get replied with the UUID as user_id on the authorize call
The authorize call:

```
curl \ 
[...] \
-H 'Content-Type:application/x-www-form-urlencoded' \
-X POST 'https://<server>/index.php/apps/oauth2/api/v1/token' \
--data-binary 'grant_type=authorization_code&code=<code>&redirect_uri=<redirecrtion_url>'
```

... on an LDAP backed account is getting replied:

```
{
    "access_token": "<access_token>",
    "expires_in": 3600,
    "message_url": "https://<server>/index.php/apps/oauth2/authorization-successful",
    "refresh_token": "<refresh_token>",
    "token_type": "Bearer",
    "user_id": "b8df1298-8742-1034-8cb4-39af73a96b9a"
}
```

Notice the **`"user_id": "b8df1298-8742-1034-8cb4-39af73a96b9a"`** taking LDAP's UUID instead of the display name. It will be used instead the display_name in the client with all the effects:

client_uuid

... but not that severe since the user supports it in the `user` query parameter:

<p align="center">
  
</p>

See https://github.com/owncloud/client/issues/5413 -> https://github.com/owncloud/client/commit/084146756bb9637ef32f229281d053394389efc1

### LINKED ISSUE #76: Change error message when logged in as wrong user
Should say: "You are logged in as '**user**' but the application requested access for user '**user**'. Please switch to the requested user using the button below to continue the authorization process."

If this is too long, drop the second sentence.

Thanks!

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #74
fixes #76 

imageedit_2_4715418700

### CODE REVIEW

**Comment by jesmrec** [comment]
By performing the following steps over Desktop client:

1.- Connect to a server with LDAP using Desktop client. User id is UUID in LDAP dashboard. 
Correct connection is stablished and UUID shown:

screen shot 2017-10-09 at 14 01 05

2.- In web UI, login as admin and change LDAP internal username from UUID to UID:

screen shot 2017-10-09 at 13 45 29

and sync LDAP: `sudo -u www-data php /opt/owncloud/occ user:sync <LDAP_backend>`

Current: 

Request of switching user with UUID:

screen shot 2017-10-09 at 11 16 26


Expected: the one in description https://github.com/owncloud/oauth2/pull/90#issue-263165621

Tested with a 10.0.3 server (stable) including current patch

NOTE: any other way to force an user switching?. By the description i guess the scope of the current PR only affects the user switching view. 

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
> By the description i guess the scope of the current PR only affects the user switching view.

the scope is only user switching - the uid is nowhere else being displayed

**Comment by DeepDiver1975** [comment]
> 2.- In web UI, login as admin and change LDAP internal username from UUID to UID:
> 
> screen shot 2017-10-09 at 13 45 29
> 
> and sync LDAP: sudo -u www-data php /opt/owncloud/occ user:sync <LDAP_backend>

is there a displayname set? If no display name is set the uid will be shown

**Comment by jesmrec** [comment]
yes, display name is set:

´{
    "ocs": {
        "data": {
            "display-name": "aaliyah beer", 
            "email": null, 
            "id": "b8e315dc-8742-1034-8cc7-39af73a96b9a"
        }, 
        "meta": {
            "itemsperpage": "", 
            "message": "OK", 
            "status": "ok", 
            "statuscode": 100, 
            "totalitems": ""
        }
    }`
}

**Comment by DeepDiver1975** [comment]
@jesmrec please post the url of the switch user page

This works: https://cloud.example.com:xxxx/index.php/apps/oauth2/authorize?response_type=code&client_id=xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69&redirect_uri=xxx&user=b6cc316a-9fe8-1035-80d3-b17d78c6049c


bildschirmfoto von 2017-10-09 19-53-02

**Comment by jesmrec** [comment]
this is the one i got from the steps:

https://server:8888/index.php/apps/oauth2/authorize?response_type=code&client_id=xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69&redirect_uri=xxxx&user=b8e80f92-8742-1034-8ce5-39af73a96b9a

**Comment by jesmrec** [comment]
- If the LDAP internal username is UUID -> works OK
- If the LDAP internal username is, for example, uid -> shows the UUID like using these steps: https://github.com/owncloud/oauth2/pull/90#issuecomment-335145766

**Comment by DeepDiver1975** [comment]
See you Changing the uid after setting up the Client? This will never Work and is not supported

**Comment by jesmrec** [comment]
yes, i did that. If it is not supported, the other case is correct and works for me.

The wording change of https://github.com/owncloud/oauth2/issues/76 is also OK 

So... 👍 

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
> We should not display anything in the "user name" field on the authentication login form then; for the best 😞

well - I have no idea if the given user id can be used as login name or not. Either we put something in or not.

lets move this thing out to the user base and wait for feedback.

**Pull request merged**
