### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by DeepDiver1975**
# DONT MERGE

:wink:

### CODE REVIEW

**Comment by joneug** [comment]
Sorry! :see_no_evil:

**Comment by DeepDiver1975** [comment]
aha

**Comment by DeepDiver1975** [comment]
:boom: 

````
 mv owncloud-app_oauth2 oauth2

mv: cannot stat ‘owncloud-app_oauth2’: No such file or directory

The command "mv owncloud-app_oauth2 oauth2" failed and exited with 1 during .

Your build has been stopped.

**Comment by joneug** [comment]
Fixing...

**Pull request merged**
