### PR TITLE
Allow http://localhost:* as valid redirect url

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes https://github.com/owncloud/oauth2/issues/29

### CODE REVIEW

**Comment by ogoffart** [comment]
Thanks. :+1:  from me.

That's only the first part of #29.   (the second part being having the client pre-registered)

**Comment by ogoffart** [comment]
(thinking about it, the "allow subdomains" checkbox could also be written  *.example.com)

(And this only allow a different port on localhost,  but not on example.com:*   But i guess that's not so useful, at least i don't need it)

**Comment by DeepDiver1975** [comment]
> the second part being having the client pre-registered

we do this in a second pr. do you plan to store client id and secret in the code base or in config?
I could think about the scenario where someone wants to recreate them for one specific installation.

**Comment by joneug** [comment]
Looks good! 👍
I think a test for the changes in `validateRedirectUri` needs to be added otherwise codecov will complain once CI finished.

**Pull request merged**
