### PR TITLE
return proper error description for auth-core/refresh-token errors

### PR DESCRIPTION
**Pull request by mrow4a**
fixes https://github.com/owncloud/enterprise/issues/4135

### CODE REVIEW

**Comment by VicDeo** [comment]
@mrow4a if those descriptions are supposed to be exposed to the user it would be good to have them translated.

**Comment by mrow4a** [comment]
> @mrow4a if `error_description` is supposed to be exposed to the user it would be good to have it translated.

hmm, this is usually debugging information that is returned by OAuth. They are rather not translated.

**Review by VicDeo — APPROVED** [review]

**Comment by mrow4a** [comment]
@micbar can be merged?

**Comment by micbar** [comment]
yes, all green

**Pull request merged**
