### PR TITLE
 Only try to getParams() for get requests - otherwise it tries to parse the request body

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by SamuAlfageme** [comment]
@DeepDiver1975 public upload (w/ and wo/ listing permissions) working as a charm. 👍 

I'm getting a log entry on the apps list about oauth2 not sure if related to the branch not being signed:

```
"url":"/settings/apps/list?category=enabled",
"message":"file_get_contents(/var/www/owncloud/apps/oauth2/appinfo/signature.json): failed to open stream: No such file or directory at /var/www/owncloud/lib/private/IntegrityCheck/Helpers/FileAccessHelper.php#39
```

**Comment by DeepDiver1975** [comment]
> "message":"file_get_contents(/var/www/owncloud/apps/oauth2/appinfo/signature.json): failed to open stream: No such file or directory at /var/www/owncloud/lib/private/IntegrityCheck/Helpers/FileAccessHelper.php#39

this is because the app is not signed -> ignore

**Comment by DeepDiver1975** [comment]
did you reverify the fully oauth flow?
Just to make sure we dont break anything else - THX

**Comment by SamuAlfageme** [comment]
@DeepDiver1975 yup, edited the comment to explicitly say so. Everything looking shiny.

**Pull request merged**
