### PR TITLE
Release 0.4.4

### PR DESCRIPTION
**Pull request by jnweiger**
Closing #256

### CODE REVIEW

**Comment by jnweiger** [comment]
> [CLA assistant check](https://cla-assistant.io/owncloud/oauth2?pullRequest=272)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/oauth2?pullRequest=272) before we can accept your contribution.
> **1** out of **2** committers have signed the CLA.
> 
> white_check_mark HanaGemela
> x jnweiger
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/oauth2?pullRequest=272) it.

I don't think, I ever signed a CLA. Why is this now important here?

**Comment by micbar** [comment]
you have forgotten. A lot of repos have the CLA check

**Comment by jnweiger** [comment]
> you have forgotten. A lot of repos have the CLA check
I am forgetful. Sorry. Do I need to do something?

**Comment by jnweiger** [comment]
@micbar @phil-davis Most of the CI pipelines in oauth2 run on php-71 and fail. the 7.2 and 7.3 pipelines work fine.
I suggest to drop 7.1 there and add 7.4 instead.

**Comment by phil-davis** [comment]
master branch has unit tests for PHP 7.2 7.3 7.4 - the change was made 6 months ago in #259 

Somehow this 0.4.4 branch is old, and has an out-of-date drone. Why is there still a release branch that is 6 months old?

**Comment by jnweiger** [comment]
> master branch has unit tests for PHP 7.2 7.3 7.4 - the change was made 6 months ago in #259
> 
> Somehow this 0.4.4 branch is old, and has an out-of-date drone. Why is there still a release branch that is 6 months old?

The branch was probably never updated since it was branched. It is not "old and still there", it is finally done!

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
We should not take 6 months to finish releases!

**Pull request merged**
